# coding: utf-8

"""
    Model Integration Software ToolKit - Agent

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from mistk.agent.client.models.data_record import DataRecord  # noqa: F401,E501
from mistk.agent.client.models.data_record_list import DataRecordList  # noqa: F401,E501


class MistkDataRecordList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'items': 'list[DataRecord]',
        'continue_token': 'str'
    }

    attribute_map = {
        'items': 'items',
        'continue_token': 'continueToken'
    }

    def __init__(self, items=None, continue_token=None):  # noqa: E501
        """MistkDataRecordList - a model defined in Swagger"""  # noqa: E501

        self._items = None
        self._continue_token = None
        self.discriminator = None

        if items is not None:
            self.items = items
        if continue_token is not None:
            self.continue_token = continue_token

    @property
    def items(self):
        """Gets the items of this MistkDataRecordList.  # noqa: E501


        :return: The items of this MistkDataRecordList.  # noqa: E501
        :rtype: list[DataRecord]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this MistkDataRecordList.


        :param items: The items of this MistkDataRecordList.  # noqa: E501
        :type: list[DataRecord]
        """

        self._items = items

    @property
    def continue_token(self):
        """Gets the continue_token of this MistkDataRecordList.  # noqa: E501


        :return: The continue_token of this MistkDataRecordList.  # noqa: E501
        :rtype: str
        """
        return self._continue_token

    @continue_token.setter
    def continue_token(self, continue_token):
        """Sets the continue_token of this MistkDataRecordList.


        :param continue_token: The continue_token of this MistkDataRecordList.  # noqa: E501
        :type: str
        """

        self._continue_token = continue_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MistkDataRecordList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MistkDataRecordList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
