name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'
        
    - name: Build wheel
      run: make -f Release_Makefile dist
      
    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: mistk-py3-none-any-${{ github.sha }}.whl
        path: dist/mistk/mistk-*-py3-none-any.whl

